from typing import List, Any
from src.parser.ast import ASTNode, CreateTableStatement, InsertStatement, SelectStatement
from src.execution.catalog import Catalog
from src.record.types import TypeId
from src.record.column import Column
from src.record.schema import Schema
from src.record.tuple import Tuple

class Executor:
    """
    Executor walks the Abstract Syntax Tree (AST) generated by the Parser 
    and performs the corresponding physical actions using the Catalog and Storage layers.
    """
    def __init__(self, catalog: Catalog):
        self.catalog = catalog

    def execute(self, statement: ASTNode) -> str | List[List[Any]]:
        if isinstance(statement, CreateTableStatement):
            return self._execute_create_table(statement)
        elif isinstance(statement, InsertStatement):
            return self._execute_insert(statement)
        elif isinstance(statement, SelectStatement):
            return self._execute_select(statement)
        else:
            raise Exception(f"Unsupported statement type: {type(statement)}")

    def _execute_create_table(self, stmt: CreateTableStatement) -> str:
        columns = []
        for col_def in stmt.columns:
            try:
                type_id = TypeId[col_def.data_type]
            except KeyError:
                raise Exception(f"Unsupported data type: {col_def.data_type}")
            columns.append(Column(col_def.name, type_id, col_def.length))
        
        schema = Schema(columns)
        self.catalog.create_table(stmt.table_name, schema)
        return f"Table '{stmt.table_name}' created successfully."

    def _execute_insert(self, stmt: InsertStatement) -> str:
        schema = self.catalog.get_schema(stmt.table_name)
        table = self.catalog.get_table(stmt.table_name)
        
        if len(stmt.values) != schema.get_column_count():
            raise Exception(f"Insert expected {schema.get_column_count()} values, got {len(stmt.values)}")
            
        t = Tuple(stmt.values)
        data = t.serialize(schema)
        rid = table.insert_tuple(data)
        
        return f"1 row inserted. (Record ID: {rid})"

    def _execute_select(self, stmt: SelectStatement) -> List[List[Any]]:
        schema = self.catalog.get_schema(stmt.table_name)
        table = self.catalog.get_table(stmt.table_name)
        
        # Determine which columns to output
        output_indices = []
        header = []
        if "*" in stmt.columns:
            output_indices = list(range(schema.get_column_count()))
            header = [col.column_name for col in schema.columns]
        else:
            for col_name in stmt.columns:
                found = False
                for idx, col in enumerate(schema.columns):
                    if col.column_name == col_name:
                        output_indices.append(idx)
                        header.append(col_name)
                        found = True
                        break
                if not found:
                    raise Exception(f"Column '{col_name}' does not exist in table '{stmt.table_name}'")

        results = [header] # The first row is the header
        for rid, tuple_data in table.iterator():
            deserialized_tuple = Tuple(schema=schema, data=tuple_data)
            
            # Filter output columns
            row = [deserialized_tuple.values[idx] for idx in output_indices]
            results.append(row)
            
        return results
